"""Stand up the Runtime fleet: one container, one Runtime process per person.

Generates two files and starts the service:

* ``fleet.yml`` -- a single ``runtime-fleet`` service. Its environment is copied
  from the hand-written base compose's ``runtime`` service, so the fleet cannot
  drift away from the single-instance configuration; only the values profile for
  this character is added on top.
* ``people.json`` -- the sessions the fleet serves, which the supervisor keeps as
  its source of truth (provision/deprovision rewrite it).

Per-person ports are 8787 upward and stay inside the compose network; the plugin
reaches them through the fleet's hostname. Only the control surface (8800) is
published, because that is the only one a human needs to poke.

Usage::

    python3 scripts/build_runtime_fleet.py --people 20001-20010 \\
        --compose /home/bomomo/astrbot_test/astrbot.yml \\
        --fleet /home/bomomo/astrbot_test/fleet.yml \\
        --data /home/bomomo/astrbot_test/fleet-data \\
        --checkout /home/bomomo/astrbot_test/src/xiaojiujiu
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

SESSION_TEMPLATE = "default:FriendMessage:{person}"

#: The character's values profile. Values are seeded into a Runtime's state *once*,
#: when its database is created, so the fleet sets them here -- a person
#: provisioned later gets them too, and an existing instance is unaffected.
VALUES = {
    "CR_VALUES__USER_CARE": "0.90",
    "CR_VALUES__RELATIONSHIP_MAINTENANCE": "0.85",
    "CR_VALUES__BOUNDARY_RESPECT": "0.92",
    "CR_VALUES__STABILITY_COMMITMENT": "0.85",
    "CR_VALUES__EMOTIONAL_EXPRESSION": "0.30",
    "CR_VALUES__CONFLICT_DIRECTNESS": "0.55",
    "CR_VALUES__AUTONOMY": "0.75",
    "CR_VALUES__CURIOSITY": "0.70",
}

#: Beta sampling cadence. A Runtime's own scheduler sleeps up to
#: ``max_interval_seconds`` (5400 by default) and a user message does *not* wake it,
#: so a week at the default would hold a handful of verdicts per person -- too thin
#: to read why the character did or did not act. Lowering the ceiling does not change
#: what she does: the hazard is integrated between decisions and is frequency
#: independent by design (two short intervals keep the survival probability of one
#: long one), so this only buys resolution. 900s = at least 96 verdicts per person
#: per day, still one or two orders of magnitude below the raw event volume.
SCHEDULER_ENV = {
    "CR_SCHEDULER__MIN_INTERVAL_SECONDS": "60",
    "CR_SCHEDULER__MAX_INTERVAL_SECONDS": "900",
}


def expand(people: str) -> list[str]:
    """Expand ``20001,20003-20010`` into a de-duplicated list of ids."""
    result: list[str] = []
    for chunk in people.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        if "-" in chunk:
            start, end = chunk.split("-", 1)
            result.extend(str(number) for number in range(int(start), int(end) + 1))
        else:
            result.append(chunk)
    unique: dict[str, None] = {}
    for item in result:
        unique.setdefault(item, None)
    return list(unique)


def base_environment(compose: Path) -> tuple[str, list[str]]:
    """Return the base Runtime image and its environment lines (minus its session)."""
    lines = compose.read_text(encoding="utf-8").splitlines()
    image = ""
    env: list[str] = []
    in_runtime = False
    in_env = False
    for line in lines:
        if line.startswith("  ") and not line.startswith("    ") and line.strip().endswith(":"):
            in_runtime = line.strip() == "runtime:"
            in_env = False
            continue
        if not in_runtime:
            continue
        if line.strip() == "environment:":
            in_env = True
            continue
        if in_env:
            if line.startswith("      ") and ":" in line:
                if not line.strip().startswith("CR_CONVERSATION_ID"):
                    env.append(line)
                continue
            if line.strip() and not line.startswith("      "):
                in_env = False
        if not image and line.strip().startswith("image:"):
            image = line.split("image:", 1)[1].strip()
    if not image or not env:
        sys.exit("could not read the base runtime service (image or environment)")
    return image, env


def render(image: str, env: list[str], compose: Path, checkout: Path) -> str:
    """Render the fleet compose file."""
    lines = [
        "# Generated by scripts/build_runtime_fleet.py -- re-run it instead of editing.",
        "# One container, one Runtime process per person: a Runtime holds one",
        "# character's memory and state, so isolation is per instance, not per container.",
        "services:",
        "  runtime-fleet:",
        f"    image: {image}",
        "    container_name: xxj-runtime-fleet",
        "    restart: unless-stopped",
        "    entrypoint:",
        "      - python",
        "      - /fleet/runtime_fleet.py",
        "      - --advertise-host",
        "      - runtime-fleet",
        "      - --people-file",
        "      - /fleet-data/people.json",
        "    environment:",
        *env,
        *[f"      {key}: {value}" for key, value in VALUES.items()],
        *[f"      {key}: {value}" for key, value in SCHEDULER_ENV.items()],
        "    volumes:",
        f"      - {checkout}/scripts:/fleet:ro",
        f"      - {compose.parent}/fleet-data:/fleet-data",
        "      - runtime-fleet-data:/data",
        "      - /etc/localtime:/etc/localtime:ro",
        "    ports:",
        "      - \"8800:8800\"    # control surface; per-person ports stay in the network",
        "    networks: [test_net]",
        "",
        "volumes:",
        "  runtime-fleet-data:",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    """Entry point."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--people", required=True, help="ids, e.g. 20001-20010")
    parser.add_argument("--compose", default="/home/bomomo/astrbot_test/astrbot.yml")
    parser.add_argument("--fleet", default="/home/bomomo/astrbot_test/fleet.yml")
    parser.add_argument("--data", default="/home/bomomo/astrbot_test/fleet-data")
    parser.add_argument("--checkout", default="/home/bomomo/astrbot_test/src/xiaojiujiu")
    parser.add_argument("--project", default="astrbot_test")
    parser.add_argument("--no-start", action="store_true")
    args = parser.parse_args()

    compose = Path(args.compose)
    data = Path(args.data)
    image, env = base_environment(compose)
    people = [SESSION_TEMPLATE.format(person=item) for item in expand(args.people)]
    print(f"image={image} env_lines={len(env)} people={len(people)}")

    Path(args.fleet).write_text(
        render(image, env, compose, Path(args.checkout)),
        encoding="utf-8",
        newline="\n",
    )
    print("wrote", args.fleet)

    data.mkdir(parents=True, exist_ok=True)
    people_file = data / "people.json"
    existing: list[str] = []
    if people_file.exists():
        try:
            existing = json.loads(people_file.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            existing = []
    merged = list(dict.fromkeys([*existing, *people]))
    payload = json.dumps(merged, ensure_ascii=False, indent=2)
    # The container runs as uid 10001 and owns this file, so the host user cannot
    # rewrite it: write through a root helper and hand ownership back afterwards.
    subprocess.run(
        ["docker", "run", "--rm", "-i", "-v", f"{data}:/d", "alpine", "sh", "-c",
         "cat > /d/people.json && chown -R 10001:10001 /d"],
        input=payload,
        check=True,
        capture_output=True,
        text=True,
    )
    print(f"wrote {people_file} ({len(merged)} people)")

    if args.no_start:
        return 0
    result = subprocess.run(
        ["docker", "compose", "-f", str(compose), "-f", args.fleet, "-p", args.project,
         "up", "-d", "runtime-fleet"],
        capture_output=True,
        text=True,
    )
    print((result.stdout or "")[-300:] or (result.stderr or "")[-300:])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
